### PR TITLE
Update README with info for zsh completion

### PR DESCRIPTION
**Pull request by patrick96**

### CODE REVIEW

**Comment by patrick96** [comment]
Don't mind my messy commit history, still new to the whole colaboration thing

**Comment by SamMorrowDrums** [comment]
Awesome, I am really glad to see someone working on the ZSH completion - I felt bad about never getting further than the basic tool!

**Comment by SamMorrowDrums** [comment]
Checking it out now - something feels very great/wrong about using gh to do this!
screen shot 2016-08-05 at 14 34 13

**Comment by patrick96** [comment]
Yeah, especially, since it didn't autocomplete for you ;)

**Comment by SamMorrowDrums** [comment]
It works great!

I only have one bit of feedback. Currently if Github returns an error message you get bad output from jsawk: 

```
gh dsfasdfasdfasdfasdf /tmp/tmp.1XZtrG:1265: TypeError: RS.pop is not a function
/tmp/tmp.EicgeT:1265: TypeError: RS.pop is not a function
/tmp/tmp.Inyapv:1265: TypeError: RS.pop is not a function
```

I tried a bunch of things (for some reason when you get an object back from the server, it seems to come back as an array (I'm not very familiar with jsawk). That threw me for a while, but in the end I worked out if I check the first item for a message property, and then return an empty result set, it mitigates this issue (and ZSH just flashes).

```javascript
javascript='return this[0].message ? [] : this.reduce(function(prev, cur, curI, array) {return prev + "\n" + cur.name + "[" + (!cur.description? cur.name + " has no description" : cur.description) + "]";}, "")'
_repos=(${(f)$(echo $repos | jsawk -a $javascript)})
```

Something like this would help make it run smoother.

**Comment by patrick96** [comment]
You are right, forgot to test for that case.
Your solution works, was also the first thing that came to my mind, but I used a simpler and more general approach. I just added the `--fail` flag to curl which will return nothing to stdout if it receives an HTTP error code (like 404).
Fix should be up in a sec

**Comment by SamMorrowDrums** [comment]
Oh yeah, much better! I did wonder why nothing was happening with error
code - I figured surely Github do send one!

**Pull request merged**
