### PR TITLE
Add support for gitlab

### PR DESCRIPTION
**Pull request by dgmora**
Quite rudimentary (updates welcome 😄), but it'd be nice that you can have both `gl` and `gh`

### CODE REVIEW

**Comment by dickeyxxx** [comment]
I think it would be best to have a separate file for `gl` like we have for fish

**Comment by dgmora** [comment]
What would your preferred way to share the code between the two files? Or just have the same in both?

**Comment by dickeyxxx** [comment]
I don't think it's worth the added complexity in a shell script

**Comment by dgmora** [comment]
Updated

**Pull request merged**
